"""empty message

Revision ID: 157cb0ad1620
Revises: 1cac3be3cc7c
Create Date: 2022-10-10 19:20:52.416855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157cb0ad1620'
down_revision = '1cac3be3cc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('competition', 'profile_image_url')
    # ### end Alembic commands ###
