"""empty message

Revision ID: 318e7fdb7c41
Revises: 9e50d6d65efa
Create Date: 2022-10-18 16:56:02.301305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318e7fdb7c41'
down_revision = '9e50d6d65efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition', 'stage',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Enum('inscripción_abierta', 'inscripción_cerrada', 'competición_finalizada', name='stages'),
               existing_nullable=False)
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('competition', 'stage',
               existing_type=sa.Enum('inscripción_abierta', 'inscripción_cerrada', 'competición_finalizada', name='stages'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
