"""empty message

Revision ID: 50e22266c3c9
Revises: cf5d274a60b8
Create Date: 2022-10-27 16:26:16.964098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e22266c3c9'
down_revision = 'cf5d274a60b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition_user', 'competitor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('competition_user', 'competitor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
