"""empty message

Revision ID: 536a9323b185
Revises: bf8c14a38a73
Create Date: 2022-10-05 17:48:50.698303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '536a9323b185'
down_revision = 'bf8c14a38a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition', 'category',
               existing_type=postgresql.ENUM('rx_femenino', 'rx_masculino', 'scalled_femenino', 'scalled_masculino', 'elite_femenino', 'elite_masculino', 'equipos', name='category'),
               nullable=False)
    op.alter_column('competitor', 'rol',
               existing_type=postgresql.ENUM('administration', 'competitor', name='rol'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitor', 'rol',
               existing_type=postgresql.ENUM('administration', 'competitor', name='rol'),
               nullable=True)
    op.alter_column('competition', 'category',
               existing_type=postgresql.ENUM('rx_femenino', 'rx_masculino', 'scalled_femenino', 'scalled_masculino', 'elite_femenino', 'elite_masculino', 'equipos', name='category'),
               nullable=True)
    # ### end Alembic commands ###
