"""empty message

Revision ID: a848c3b61ff9
Revises: d5322ea0b69c
Create Date: 2022-11-07 18:46:32.970749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a848c3b61ff9'
down_revision = 'd5322ea0b69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
