"""empty message

Revision ID: b41ee17666f1
Revises: 9e50d6d65efa
Create Date: 2022-10-18 11:36:49.650686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41ee17666f1'
down_revision = '9e50d6d65efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('poster_image_url', sa.String(length=255), nullable=True))
    op.drop_column('competition', 'profile_image_url')
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('competition', sa.Column('profile_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('competition', 'poster_image_url')
    # ### end Alembic commands ###
