"""empty message

Revision ID: bf8c14a38a73
Revises: 
Create Date: 2022-10-03 14:47:13.419193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c14a38a73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('vat', sa.Integer(), nullable=True),
    sa.Column('rol', sa.Enum('administration', 'competitor', name='rol'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(length=120), nullable=False),
    sa.Column('qualifier_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=False),
    sa.Column('category', sa.Enum('rx_femenino', 'rx_masculino', 'scalled_femenino', 'scalled_masculino', 'elite_femenino', 'elite_masculino', 'equipos', name='category'), nullable=True),
    sa.Column('requirements', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('adress', sa.String(length=240), nullable=True),
    sa.Column('gender', sa.Enum('masculino', 'femenino', name='gender'), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('rol', sa.Enum('administration', 'competitor', name='rol'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('qualifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(length=240), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('previous_result', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('competition_competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifier_competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualifier_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['qualifier_id'], ['qualifier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualifier_competitor')
    op.drop_table('competition_competitor')
    op.drop_table('user')
    op.drop_table('qualifier')
    op.drop_table('competitor')
    op.drop_table('competition')
    op.drop_table('administration')
    # ### end Alembic commands ###
