"""empty message

Revision ID: dfb855aa9381
Revises: 50e22266c3c9
Create Date: 2022-10-27 16:39:05.688129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb855aa9381'
down_revision = '50e22266c3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.String(),
               type_=sa.Enum('competitor', 'administration', name='name'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rol',
               existing_type=sa.Enum('competitor', 'administration', name='name'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
